
/**
 * Hello.java .
 * Generated by the IDL-to-Java compiler (portable), version "3.2"
 * from hello.idl
 * jeudi 13 octobre 2022 08 h 55 WET
 */

public interface Hello extends HelloOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity
{
} // interface Hello
