
/**
 * HelloOperations.java .
 * Generated by the IDL-to-Java compiler (portable), version "3.2"
 * from hello.idl
 * jeudi 13 octobre 2022 08 h 55 WET
 */

public interface HelloOperations
{
    void hello ();
} // interface HelloOperations
